import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:myportfolio/app/ambience.dart';
import 'package:myportfolio/app/theme/lighting.dart';

void main() {
  group('Ambience', () {
    test('is silent by default', () {
      final player = RecordingPlayer();
      final a = Ambience(player: player)..enterScene(SceneLighting.day);
      expect(a.enabled, isFalse);
      expect(a.track, isNull);
      expect(player.played, isEmpty);
    });

    test('starts the scene loop only once enabled', () {
      final player = RecordingPlayer();
      final a = Ambience(player: player)..enterScene(SceneLighting.night);
      expect(player.played, isEmpty);

      a.toggle();
      expect(a.enabled, isTrue);
      expect(a.track, 'room-night');
      expect(player.played, ['room-night']);
    });

    test('follows the world as the lighting changes', () {
      final player = RecordingPlayer();
      final a = Ambience(player: player)
        ..enterScene(SceneLighting.day)
        ..toggle();
      a.enterScene(SceneLighting.sunset);
      a.enterScene(SceneLighting.interior);
      expect(player.played, ['valley-day', 'valley-sunset', 'room-interior']);
    });

    test('muting stops playback and clears the track', () {
      final player = RecordingPlayer();
      final a = Ambience(player: player)
        ..enterScene(SceneLighting.day)
        ..toggle();
      a.toggle();
      expect(a.enabled, isFalse);
      expect(a.track, isNull);
      expect(player.stops, greaterThan(0));
    });

    test('re-entering the same scene does not restart the loop', () {
      final player = RecordingPlayer();
      final a = Ambience(player: player)
        ..enterScene(SceneLighting.day)
        ..toggle();
      a.enterScene(SceneLighting.day);
      expect(player.played, ['valley-day']);
    });

    test('every lighting state has a loop', () {
      for (final l in SceneLighting.values) {
        expect(Ambience.trackFor(l), isNotEmpty);
      }
      final names = SceneLighting.values.map(Ambience.trackFor).toSet();
      expect(names.length, SceneLighting.values.length);
    });

    test('disposing the controller releases the audio backend', () {
      final player = RecordingPlayer();
      Ambience(player: player).dispose();
      expect(player.disposed, isTrue);
    });

    test('notifies listeners on toggle and on scene change', () {
      final a = Ambience(player: RecordingPlayer());
      var n = 0;
      a.addListener(() => n++);
      a
        ..enterScene(SceneLighting.day)
        ..toggle()
        ..toggle();
      expect(n, 3);
    });
  });

  group('ambience assets', () {
    // The loops are generated by tool/generate_ambience.py rather than sampled,
    // so they ship with the site. These guard the wiring between the track
    // names the controller chooses and the files actually on disk.
    test('every lighting state has a bundled loop', () {
      for (final lighting in SceneLighting.values) {
        final file = File('assets/audio/${Ambience.trackFor(lighting)}.ogg');
        expect(file.existsSync(), isTrue,
            reason: 'missing ${file.path} for $lighting');
      }
    });

    test('loops are small enough to fetch on demand', () {
      // Each loop is a 28.8-second scored piece, not a texture bed, so it
      // costs more than wind would. Only the current scene's loop is ever
      // fetched, and only once ambience is switched on, so the number that
      // matters is the per-file one rather than the total.
      for (final lighting in SceneLighting.values) {
        final file = File('assets/audio/${Ambience.trackFor(lighting)}.ogg');
        final kb = file.lengthSync() / 1024;
        expect(kb, lessThan(200), reason: '${file.path} is ${kb.round()} KB');
        expect(kb, greaterThan(4), reason: '${file.path} looks truncated');
      }
    });

    test('the audio directory holds nothing unreferenced', () {
      final referenced = {
        for (final l in SceneLighting.values) '${Ambience.trackFor(l)}.ogg',
      };
      final onDisk = Directory('assets/audio')
          .listSync()
          .whereType<File>()
          .map((f) => f.uri.pathSegments.last)
          .toSet();
      expect(onDisk.difference(referenced), isEmpty,
          reason: 'unused audio would ship for no reason');
    });
  });
}
